export const SLATE_USE_EDITOR = Symbol("SLATE_USE_EDITOR");

export const SLATE_USE_ELEMENT = Symbol("SLATE_USE_ELEMENT");

export const SLATE_USE_FOCUSED = Symbol("SLATE_USE_FOCUSED");

export const SLATE_USE_COMPOSING = Symbol("SLATE_USE_COMPOSING");

export const SLATE_USE_READ_ONLY = Symbol("SLATE_USE_READ_ONLY");

export const SLATE_USE_SELECTION = Symbol("SLATE_USE_SELECTION");

export const SLATE_INNER_RENDER_ELEMENT = Symbol("SLATE_INNER_RENDER_ELEMENT");
export const SLATE_INNER_RENDER_LEAF = Symbol("SLATE_INNER_RENDER_LEAF");
export const SLATE_INNER_RENDER_PLACEHOLDER = Symbol(
  "SLATE_INNER_RENDER_PLACEHOLDER",
);
export const SLATE_INNER_RENDER_TEXT = Symbol("SLATE_INNER_RENDER_TEXT");
export const SLATE_INNER_RENDER_CHUNK = Symbol("SLATE_INNER_RENDER_CHUNK");
export const SLATE_INNER_STATIC_CHUNK_ROOT = Symbol(
  "SLATE_INNER_STATIC_CHUNK_ROOT",
);
export const SLATE_INNER_RENDER_DECORATE = Symbol(
  "SLATE_INNER_RENDER_DECORATE",
);

export const SLATE_INNER_EDITOR_VERSION = Symbol("SLATE_INNER_EDITOR_VERSION");
export const SLATE_INNER_MARK_PLACEHOLDER = Symbol(
  "SLATE_INNER_MARK_PLACEHOLDER",
);
export const SLATE_INNER_PLACEHOLDER = Symbol("SLATE_INNER_PLACEHOLDER");
export const SLATE_INNER_PLACEHOLDER_SHOW = Symbol(
  "SLATE_INNER_PLACEHOLDER_SHOW",
);
export const SLATE_INNER_PLACEHOLDER_RESIZE = Symbol(
  "SLATE_INNER_PLACEHOLDER_RESIZE",
);
