export const SLATE_USE_EDITOR = Symbol("SLATE_USE_EDITOR");

export const SLATE_USE_ELEMENT = Symbol("SLATE_USE_ELEMENT");

export const SLATE_USE_FOCUSED = Symbol("SLATE_USE_FOCUSED");

export const SLATE_USE_COMPOSING = Symbol("SLATE_USE_COMPOSING");

export const SLATE_USE_READ_ONLY = Symbol("SLATE_USE_READ_ONLY");

export const SLATE_USE_SELECTION = Symbol("SLATE_USE_SELECTION");
