export const SLATE_USE_EDITOR = Symbol("SLATE_USE_EDITOR");

export const SLATE_USE_DECORATE = Symbol("SLATE_USE_DECORATE");

export const SLATE_USE_SELECTED = Symbol("SLATE_USE_SELECTED");

export const SLATE_USE_SELECTION = Symbol("SLATE_USE_SELECTION");

export const SLATE_STATE_FOCUS = Symbol("SLATE_STATE_FOCUS");

export const SLATE_STATE_COMPOSING = Symbol("SLATE_STATE_COMPOSING");

export const SLATE_STATE_READ_ONLY = Symbol("SLATE_STATE_READ_ONLY");

export const SLATE_STATE_SELECTION = Symbol("SLATE_STATE_SELECTION");


export const SLATE_INNER_RENDER_ELEMENT = Symbol("SLATE_INNER_RENDER_ELEMENT");
export const SLATE_INNER_RENDER_LEAF = Symbol("SLATE_INNER_RENDER_LEAF");
export const SLATE_INNER_RENDER_PLACEHOLDER = Symbol("SLATE_INNER_RENDER_PLACEHOLDER");
export const SLATE_INNER_CHANGE_EFFECT_INJECT = Symbol("SLATE_INNER_CHANGE_EFFECT_INJECT");
export const SLATE_INNER_MARK_PLACEHOLDER = Symbol("SLATE_INNER_MARK_PLACEHOLDER");
