export const SLATE_USE_EDITOR = Symbol("SLATE_USE_EDITOR");

export const SLATE_INITIAL_VALUE = Symbol("SLATE_INITIAL_VALUE");

export const SLATE_CHANGE_EFFECT_INJECT = Symbol("SLATE_CHANGE_EFFECT_INJECT");
