name: publish package
on:
  push:
    branches:
      - master
permissions: write-all
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: 配置 Node 环境
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org/'
          node-version: "latest"
      - name: 安装 PNPM
        run: npm i -g pnpm
      - name: 安装依赖
        run: pnpm install --no-frozen-lockfile
      - name: 开始单元测试
        run: pnpm test run
      - name: 开始打包
        run: pnpm build-all
      - name: 发布npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}