name: test package
on:
  push:
    branches: [ develop ]
permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          registry-url: "https://registry.npmjs.org/"
          node-version: 'latest'
          package-manager-cache: true
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: 安装依赖
        run: pnpm install --no-frozen-lockfile

      - name: 开始单元测试
        run: pnpm test run

      - name: 准备集成测试环境
        run: pnpm playwright install --with-deps

      - name: 开始集成测试
        run: pnpm e2e

      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
